apiVersion: v1
kind: Template
metadata:
  name: f8ui-admin-console
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      service: f8ui-admin-console
    name: f8ui-admin-console
  spec:
    replicas: 2
    selector:
      service: f8ui-admin-console
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: f8ui-admin-console
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: f8ui-admin-console
          ports:
          - containerPort: 80
            protocol: TCP
          env:
            - name: ADMIN_CONSOLE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: f8ui-admin-console
                  key: admin.api.url
            - name: AUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: f8ui-admin-console
                  key:  auth.api.url
            - name: WIT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: f8ui-admin-console
                  key:  wit.api.url
            - name: SSO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: f8ui-admin-console
                  key: sso.api.url
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 10
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: f8ui-admin-console
    name: f8ui-admin-console
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: f8ui-admin-console
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      service: f8ui-admin-console
    name: f8ui-admin-console
  spec:
    host: ''
    port:
      targetPort: "8080"
    to:
      kind: Service
      name: f8ui-admin-console
      weight: 100
    wildcardPolicy: None
  status: {}
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-fabric8-ui-admin-console
- name: IMAGE_TAG
  value: latest
